In [87]:
from IPython.display import clear_output

print(['a', 'b', 'c']+[1,2,3])

#dictionary
d = {'a':'apple', 'b':'boy', 'c':'cat'}
for k,v,in d.items():
    print(k,v)

#tuples
x = ('apple', 'boy', 'cat')
a,b,c = x
a

['a', 'b', 'c', 1, 2, 3]
a apple
b boy
c cat


'apple'

In [27]:
#string formats - stings are not mutable, variable with a string value can be changed
record = {'price':3.24,'num_items':4,'person':'Chris'}

sales_statement = '{} bought {} item(s) at a price of {} each for total of {}'

print(sales_statement.format(record['person'],
                            record['num_items'],
                            record['price'],
                            record['price']*record['num_items']))

Chris bought 4 item(s) at a price of 3.24 each for total of 12.96


In [94]:
#files

import csv

%precision 2 #using ipython

with open('mpg.csv') as csvfile:
    mpg=list(csv.DictReader(csvfile))
    
mpg[:3]

[OrderedDict([('mpg', '18'),
              ('cylinders', '8'),
              ('displacement', '307'),
              ('horsepower', '130'),
              ('weight', '3504'),
              ('acceleration', '12'),
              ('model_year', '70'),
              ('origin', '1'),
              ('name', 'chevrolet chevelle malibu')]),
 OrderedDict([('mpg', '15'),
              ('cylinders', '8'),
              ('displacement', '350'),
              ('horsepower', '165'),
              ('weight', '3693'),
              ('acceleration', '11.5'),
              ('model_year', '70'),
              ('origin', '1'),
              ('name', 'buick skylark 320')]),
 OrderedDict([('mpg', '18'),
              ('cylinders', '8'),
              ('displacement', '318'),
              ('horsepower', '150'),
              ('weight', '3436'),
              ('acceleration', '11'),
              ('model_year', '70'),
              ('origin', '1'),
              ('name', 'plymouth satellite')])]

In [36]:
print(len(mpg))

print(mpg[0].keys())

#avg city mpg

sum(float(d['mpg']) for d in mpg)/len(mpg)



398
odict_keys(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year', 'origin', 'name'])


23.51

In [96]:
cyl=set(d['model_year'] for d in mpg)
cyl

{'70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82'}

In [97]:
mpgbymodyr = []

for c in my:
    summpg = 0
    mycount = 0
    for d in mpg:
        if d['model_year'] == c:
            summpg += float(d['mpg'])
            mycount += 1
    mpgbymodyr.append((c, summpg/mycount))
        
mpgbymodyr.sort(key=lambda x: x[0])
mpgbymodyr

[('70', 17.69),
 ('71', 21.25),
 ('72', 18.71),
 ('73', 17.10),
 ('74', 22.70),
 ('75', 20.27),
 ('76', 21.57),
 ('77', 23.38),
 ('78', 24.06),
 ('79', 25.09),
 ('80', 33.70),
 ('81', 30.33),
 ('82', 31.71)]

In [104]:
#dates and times epoch:jan 1 1970

import datetime as dt
import time as tm

dtnow=dt.datetime.fromtimestamp(tm.time())
dtnow.year, dtnow.month, dtnow.hour, dtnow.minute

In [110]:
#advanced topics

class Person:
    department='School of Information'
    
    def set_name(self, new_name):
        self.name = new_name
        
    def set_location(self, new_location):
        self.location=new_location
        
#constructor __init__method
#map map(function, iterable)

In [115]:
store1=[10,11,12.34,2.34]
store2=[9, 11.10, 12.34, 2.01]

cheapest=map(min, store1, store2)
#returns map object does not try to run the function till you look inside for a value
cheapest

for m in cheapest:
    print(m)

9
11
12.34
2.01


In [150]:
people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

#4 options to get title and last name

def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[-1]

for person in people:
    print(split_title_and_name(person))

for person in people:
    print((lambda x:x.split()[0]+' '+x.split()[-1])(person))
    
l1 = list(map(split_title_and_name, people))
print(l1)

l2 = list(map(lambda x:x.split()[0]+' '+x.split()[-1], people))
print(l2)

Dr. Brooks
Dr. Collins-Thompson
Dr. Vydiswaran
Dr. Romero
Dr. Brooks
Dr. Collins-Thompson
Dr. Vydiswaran
Dr. Romero
['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']
['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']


In [161]:
#list comprehensions

my_list1=[]
for number in range(1000):
    if number%2==0:
        my_list1.append(number)
        
my_list2 = [number for number in range(1000) if number%2==0]

my_list1==my_list2

True

In [167]:
def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [i*j for i in range(10) for j in range(10)]

True

In [25]:
#numpy
import numpy as np

mylist=[[1,2,3], [4,5,6]]
x=np.array(mylist)
print(x.shape)

n = np.arange(0,30,2)
print(n)
r=n.reshape(3,5)
print(r)

o=np.linspace(0,4,9)
print(o)
o.resize(3,3) #resize changes data, reshape doesnt
print(o)

print(np.ones((1,2)))
print(np.zeros((1,2)))

print(np.eye(3))

y=[4,5,6]
print(np.diag(y))

p=np.ones([2,3], int)
print(np.vstack([p, 2*p]))
print(np.hstack([p, 2*p]))

(2, 3)
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4. ]
[[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]]
[[1. 1.]]
[[0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [73]:
#operations
x=np.array([1,2,3])
y=np.array([4,5,6])

print(x.dot(y))

z=np.array([y, y**2])

print(z.T)

print(z.std(), z.argmax(), z.argmin())

s=np.arange(13)**2
print(s)
print(s[0], s[0:3], s[-4:])

#5th from end to beginning counting backwards by 2
print(s[-5::-2])

#2D array
r=np.arange(36)
r.resize((6,6))
print(r)

print(r[2,2], r[3,3:6])

print(r[:2, :-1], r[-1, ::2])

r[r>30] =30
print(r)

#assingment will change original array, .copy() will not

r2= r[:3, :3]
r2[:] = 0
print(r)

r_copy = r.copy()
r_copy[:] = 10
print(r)


#clear_output()

In [85]:
#iterating over arrays
test = np.random.randint(0,10,(4,3))
print(test)
for row in test:
    print(row)

for i in range(len(test)):
    print(test[i])
    
for i, row in enumerate(test):
    print('row ', i, ' is ', row)
    
test2 = test**2

for i,j in zip(test, test2):
    print(i, ' + ', j, ' = ',i+j)

[[0 9 1]
 [4 6 3]
 [3 6 4]
 [1 9 6]]
[0 9 1]
[4 6 3]
[3 6 4]
[1 9 6]
[0 9 1]
[4 6 3]
[3 6 4]
[1 9 6]
row  0  is  [0 9 1]
row  1  is  [4 6 3]
row  2  is  [3 6 4]
row  3  is  [1 9 6]
[0 9 1]  +  [ 0 81  1]  =  [ 0 90  2]
[4 6 3]  +  [16 36  9]  =  [20 42 12]
[3 6 4]  +  [ 9 36 16]  =  [12 42 20]
[1 9 6]  +  [ 1 81 36]  =  [ 2 90 42]


In [92]:
x = np.arange(36).reshape(6,6)
x[2:4, 2:4]

array([[14, 15],
       [20, 21]])